export const API = {
  KTV: {
    BOOKING: '/api/ktv/booking',
    SETTINGS: '/api/ktv/settings',
    ON_CALL: '/api/ktv/on-call',
    INTERACTION: '/api/ktv/interaction',
    REVIEW: '/api/ktv/review',
    NOTIFICATIONS: (techCode: string) => `/api/ktv/notifications?techCode=${techCode}`,
    NOTIFICATION_MARK_READ: (id: string) => `/api/ktv/notifications?id=${id}`,
    WALLET: {
      BALANCE: (techCode: string) => `/api/ktv/wallet/balance?techCode=${techCode}`,
      TIMELINE: (techCode: string) => `/api/ktv/wallet/timeline?techCode=${techCode}`,
      WITHDRAW: '/api/ktv/wallet/withdraw',
      PIGGY_BANK: (techCode: string) => `/api/ktv/wallet/piggy-bank?techCode=${techCode}`,
      BONUS_BALANCE: (techCode: string) => `/api/ktv/wallet/bonus/balance?techCode=${techCode}`,
      BONUS_TIMELINE: (techCode: string) => `/api/ktv/wallet/bonus/timeline?techCode=${techCode}`,
    },
    ATTENDANCE: '/api/ktv/attendance',
    ATTENDANCE_STATUS: (employeeId: string) => `/api/ktv/attendance/status?employeeId=${employeeId}`,
    ATTENDANCE_CONFIRM: '/api/ktv/attendance/confirm',
    ATTENDANCE_PENDING: '/api/ktv/attendance/pending',
    ATTENDANCE_HISTORY: '/api/ktv/attendance/history',
    LEAVE: '/api/ktv/leave',
    SHIFT: '/api/ktv/shift',
    HISTORY: (techCode: string, from: string, to: string) =>
      `/api/ktv/history?techCode=${techCode}&dateFrom=${from}&dateTo=${to}`,
    HISTORY_UPDATE: '/api/ktv/history',
    PUSH_SYNC: '/api/ktv/push-sync',
    PUSH_UNSUB: '/api/ktv/push-unsubscribe',
    PAUSE_SWAP: '/api/ktv/pause-swap-resume',
  },
  ADMIN: {
    NOTIFICATION_RULES: '/api/admin/notification-rules',
    PIGGY_BANK: '/api/admin/piggy-bank',
    SETTINGS_SYSTEM: '/api/admin/settings/system',
    UPDATE_WIFI_IP: '/api/admin/update-wifi-ip',
  },
  SYSTEM: {
    CONFIG: '/api/system/config',
  },
  FINANCE: {
    WITHDRAWALS: '/api/finance/withdrawals',
    PAYROLL_OVERRIDE: '/api/finance/payroll/override',
    ADJUSTMENT: '/api/finance/adjustment',
    KTV_SUMMARY: '/api/finance/ktv-summary',
    KTV_BONUS_SUMMARY: '/api/finance/ktv-bonus-summary',
    PAYROLL_SHIFTS: '/api/finance/payroll/shifts',
  },
  ROOMS: '/api/rooms',
  CUSTOMERS: '/api/customers',
  CUSTOMERS_EXPORT: '/api/customers/export',
  EMPLOYEES: '/api/employees',
  STAFF_LIST: '/api/staff/list',
  TURNS: '/api/turns',
  SUPPORT: {
    TASKS: '/api/support/tasks',
  },
} as const;
